In [1]:
import numpy as np

# Given parameters
X = np.array([[10, 2, 1], [2, -5, 1], [5, 5, 1]])
D = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
W = np.array([[1, -2, 0], [0, -1, 2], [1, 3, -1]], dtype=float)  # Convert W to float
c = 0.1  # Learning rate

# Activation function
def activation(y):
    return np.tanh(y)

# Delta learning rule using outer product
for _ in range(100):  # Epochs
    for i, x in enumerate(X):
        o = activation(np.dot(x, W.T))  # Calculate output (W.T for correct shape)
        error = D[i] - o  # Compute error
        W += c * np.outer(error, x)  # Update weights using outer product

# Testing (Recall)
output = [activation(np.dot(x, W.T)) for x in X]  # Compute outputs for all inputs
print("Updated Weights:\n", W)
print("Recall Output:\n", np.array(output))


Updated Weights:
 [[ 0.72722079 -0.21957567 -4.68349677]
 [-0.99970255 -1.2007484   1.90014916]
 [-1.00107841  2.59988417 -1.20009536]]
Recall Output:
 [[ 0.9732029  -1.         -0.99998798]
 [-0.97221329  0.99998513 -1.        ]
 [-0.97297518 -0.99999998  0.99999749]]
